version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
      - VITE_API_URL=https://carbon.loganmiller.dev/api
    ports:
      - "8030:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8020:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://carbon_storage_user:${POSTGRES_PASSWORD}@gpu1:3030/carbon_storage
      - PRODUCTION_URL=postgresql+asyncpg://carbon_storage_user:${POSTGRES_PASSWORD}@192.168.70.100:3030/carbon_storage
      - ENVIRONMENT=production
      - FRONTEND_URL=https://carbon.loganmiller.dev
    volumes:
      - /home/millelog/carbon-db:/var/carbon-db