version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://backend:8020
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8020:8000"
    environment:
      - DATABASE_URL=postgresql://carbon_storage_user:${POSTGRES_PASSWORD}@localhost:3031/carbon_storage

volumes:
  postgres_data:

networks:
  default:
    name: carbon_storage_network